### ISSUE TITLE
error: ‘TUNER_NUM_PADS’ undeclared

### ISSUE THREAD

**Issue by ali1234** [AlexanderS/tbsecp3-driver#1]
This happens because those enums are no longer part of the public API after this patch:

https://git.linuxtv.org/linux.git/commit/?id=65e83fb00b2df3eadc23d71aacf626af3700f337

**Comment by ali1234** [comment]
This is the fix:

https://git.linuxtv.org/linux.git/diff/?id=552b926fa3b1671b3d3937641f0f5585e6659866

I was able to build after applying this. Haven't tested if it works yet though.

**Comment by AlexanderS** [comment]
This issue should be fixed with the current version. (After updating the sources from TBS.)
