### ISSUE TITLE
Upstream these modules?

### ISSUE THREAD

**Issue by Hoeze** [AlexanderS/tbsecp3-driver#10]
Hi @AlexanderS,
I do not know a lot about these modules' code quality, but they seem to be a limited set of files to be added to the Linux kernel.
How realistic would it be to submit these as patches to the upstream Linux kernel?

**Comment by AlexanderS** [comment]
@Hoeze You will have to ask at https://github.com/tbsdtv/linux_media. This repo only modifies the vendor provided sources to be able to build it out of tree. But I think the chances of upstreaming these modules are minimal.
