### ISSUE TITLE
Removing modules breaks the build

### ISSUE THREAD

**Issue by ali1234** [AlexanderS/tbsecp3-driver#2]
https://github.com/AlexanderS/tbsecp3-driver/commit/83f0a3022f2071371454c5671a85cff7acf05522 removes some upstream modules from the repo, but the headers for those modules are not included in the public kernel headers. This means the repo can't be built without the full kernel build tree, which is usually not available.

This works in Arch because of https://bugs.archlinux.org/task/20402 but basically no other distributions package private headers this way. Not Debian derivites and not Fedora for example.

**Comment by ali1234** [comment]
Note: it's only necessary to provide the headers. The .c files are not required. I copied the headers from Linux 5.0.0 which fixes the other bug too. Of course this isn't future-proof if the upstream headers change again. I'm not sure how to solve this properly - it's unlikely that every distro would want to include the extra headers in their linux-headers packages.

**Comment by AlexanderS** [comment]
I added the modules again. I discovered that TBS is fixing issues in their copies. So we need to overwrite the modules from the kernel. This should fix this issue.
