### ISSUE TITLE
TurboSight TBS6928SE DVB-S2 card not recognized

### ISSUE THREAD

**Issue by schrieveslaach** [AlexanderS/tbsecp3-driver#5]
I'm running a small home server that has a [TBS6928SE DVB-S2 card](https://www.tbsdtv.com/products/tbs6928se-dvb-s2-tv-tuner-ci-pcie-card.html) included. On the server runs a Ubuntu distribution with the TBS drivers. So `dmesg | grep -i dvb` gives me:

```
[   47.737508] DVB: registering new adapter (SAA716x dvb adapter)
[   48.292575] TurboSight TBS6928SE DVB-S2 card MAC=00:22:ab:e0:59:96
[   48.332983] DVB: registering adapter 0 frontend 0 (TurboSight TBS 6928SE DVBS/S2 frontend)...
```

Now, I want to use Arch Linux and I tested the tbsecp3-driver but it did not work with that card. Is it possible to include the support for this card? I would like to use this driver because it has very fast compilation times when upgrading the kernel (the server is an Atom based system to safe energy).

**Comment by schrieveslaach** [comment]
Seems to that this support depends on tbsdtv/linux_media#130.

**Comment by AlexanderS** [comment]
If this card is not supported by the open source tbs driver, I cannot do anything :confused:
