### ISSUE TITLE
Update code with changes in upstream please

### ISSUE THREAD

**Issue by SpeedProg** [AlexanderS/tbsecp3-driver#7]
I got some problems with my TBS 6902 and apparently https://github.com/tbsdtv/linux_media/commit/942af455a1fca71dc15a248dea72a94aae6dd030 fixes this. 
There is probably some other bugfixes in upstream too.
Would be nice if they could be merged down when you got time.
This out of tree driver helped me a lot.

**Comment by AlexanderS** [comment]
I have updated the code with the current upstream version in d903b517cdb6ed0b8dee6ef016a3c77f36e9e514. Can you try if this fixes your problem?

**Comment by SpeedProg** [comment]
Sadly it did actually not (the one were I can't use both cards at once), I changed to their official out of tree media tree based driver, to be able to contact their support about it.

But it did make me able to use the 2nd card I acquired on its own, which did not work before.

Didn't lead to anything, yet, through. But since I use a 6902 with the chip that was fixed there, I will need the patch in once I go back permanently to this out of tree build.
Thank you a lot for doing this.

**Comment by AlexanderS** [comment]
So it does not work with the offical media tree build from tbs, too?

Did you check if all 4 tuner works, if you disconnect your USB tuner?

**Comment by houmles** [comment]
I have a same 6902 card and this patch works for me.
Without this patch I am unable to tune almost anything.
Thanks for the update! I can finally ditch official bloated driver.

**Comment by SpeedProg** [comment]
The coded I needed was merged here.
Also if anyone cares, the (none driver missing) problem with my cards ceased to exist after I replaced all the cabeling and the splitter. (too bad it took me months till I did that)
